version: '3.8'

services:

  db:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yii2basic
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8880:80"
    volumes:
      - ./app/:/var/www/html
    depends_on:
      - db

  test:
    build: .
    entrypoint: ["bash", "-c", "codecept run"]
    depends_on:
      - app
    volumes:
      - ./tests:/var/www/html/tests

